Implemented: functionality to product store card on facility details page (#10)
hotwax/facilities pull request #14
Opened 2023-11-17 06:47 UTC by amansinghbais

### Related Issues

Closes #10

### Short Description and Why It's Useful

Made product store card dynamic and functional on the facility details page.
-  Displayed all product stores inside the modal
-  Displayed associated product stores in the product store card at facility details page.
-  Api and functionality to remove product store association with facility.
-  Api and functionality to associate a product store with facility.

### Screenshots of Visual Changes before/after (If There Are Any)

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/facilities#contribution-guideline)

2023-11-17 10:27 UTC, ymaheshwari1 requested changes

2023-11-17 10:27 UTC, ymaheshwari1 commented on src/store/modules/facility/actions.ts
> +        productStores = resp.data.docs ? resp.data.docs : []
No need to use ternary, as we will already check whether the resp has some data or not, using count param

2023-11-17 10:27 UTC, ymaheshwari1 commented on src/store/modules/facility/actions.ts
> +      console.error('Failed to fetch user associated product stores.', error)
Remove unwanted console statements

2023-11-24 08:54 UTC, ymaheshwari1 requested changes

2023-11-24 08:54 UTC, ymaheshwari1 commented on src/views/FacilityDetails.vue
> +              <ion-button @click="selectProductStore()" fill="clear">
```suggestion
              <ion-button @click="selectProductStores()" fill="clear">
```

2023-11-24 08:54 UTC, ymaheshwari1 commented on src/views/FacilityDetails.vue
> +            showToast(translate('Failed to update some facility stores'))
```suggestion
            showToast(translate('Failed to update product stores'))
```

2023-11-24 08:54 UTC, ymaheshwari1 commented on src/views/FacilityDetails.vue
> +            showToast(translate('Facility stores updated successfully.'))
```suggestion
            showToast(translate('Product stores updated successfully.'))
```

2023-11-24 08:54 UTC, ymaheshwari1 commented on src/components/ProductStorePopover.vue
> +          "thruDate": DateTime.now().toMillis()
Handle case when having error in the resp.

2023-11-27 05:27 UTC, ravilodhi commented on src/components/ProductStorePopover.vue
> +  IonIcon,
Arrange imports in alphabetical order.

2023-11-27 08:43 UTC, merged